"""Add color to dictionaries

Revision ID: 459369348fe8
Revises: a2715a613f0a
Create Date: 2025-08-27 11:21:54.078058

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459369348fe8'
down_revision: Union[str, Sequence[str], None] = 'a2715a613f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionaries', 'color')
    # ### end Alembic commands ###
