"""Add problem score

Revision ID: 846b3bdb7ab0
Revises: 459369348fe8
Create Date: 2025-09-17 16:27:31.544429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846b3bdb7ab0'
down_revision: Union[str, Sequence[str], None] = '459369348fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionaries', sa.Column('problem_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionaries', 'problem_score')
    # ### end Alembic commands ###
