"""Create tables

Revision ID: a2715a613f0a
Revises: 
Create Date: 2025-08-27 09:55:11.904415

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2715a613f0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_with_highlights', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_recording_id'), 'conversations', ['recording_id'], unique=False)
    op.create_index(op.f('ix_conversations_speaker'), 'conversations', ['speaker'], unique=False)
    op.create_table('dictionaries',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phrases', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_index(op.f('ix_dictionaries_name'), 'dictionaries', ['name'], unique=False)
    op.create_index(op.f('ix_dictionaries_type'), 'dictionaries', ['type'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recognize_status', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('recognize_start', sa.DateTime(), nullable=True),
    sa.Column('recognize_end', sa.DateTime(), nullable=True),
    sa.Column('analysis_start', sa.DateTime(), nullable=True),
    sa.Column('analysis_end', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_analysis_status'), 'recordings', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_recordings_recognize_status'), 'recordings', ['recognize_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_recognize_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_analysis_status'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_dictionaries_type'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_name'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    op.drop_table('dictionaries')
    op.drop_index(op.f('ix_conversations_speaker'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_recording_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
