"""add dictionaries table

Revision ID: c0c526e6296b
Revises: e1e8aaf4f66c
Create Date: 2025-08-18 15:40:56.226457

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c526e6296b'
down_revision: Union[str, Sequence[str], None] = 'e1e8aaf4f66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    dictionarytype = postgresql.ENUM(
        'CLIENT', 'OPERATOR', 'BOTH',
        name='dictionarytype',
        create_type=True
    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', dictionarytype, nullable=False),
    sa.Column('phrases', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_name'), 'dictionaries', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionaries_name'), table_name='dictionaries')
    op.drop_table('dictionaries')

    dictionarytype = postgresql.ENUM(
        name='dictionarytype',
        create_type=False
    )

    # Удаляем типы только если они существуют
    dictionarytype.drop(bind=op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
